language: node_js
node_js:
  - "node"
branches:
  only:
    - master
stages:
  - test
  - build
jobs:
  include:
    - stage: test
      name: react
      install:
        - cd src/client
        - npm install
      script:
        - npm test
    - stage: test
      name: server
      install:
        - cd src
        - npm install
      script:
        - npm test
    - stage: build
      name: react
      install:
        - cd src/client
        - npm install
      script:
        - npm run-script build
    - stage: build
      name: server
      install:
        - cd src
        - npm install
      script:
        - npm build
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt